-- 관리자접속
-- 2021.05.24

CREATE TABLESPACE TODOLIST
DATAFILE 'C:/oraclexe/data/iolistDB'
SIZE 1M AUTOEXTEND ON NEXT 1K ;

CREATE USER todoUser IDENTIFIED BY todoUser
DEFAULT TABLESPACE TODOLIST;

GRANT DBA TO todoUser;

